import type { Metadata } from 'next';
import { Providers } from '@/components';
import NavigationBar from '@/components/navbar/NavigationBar';
import './globals.css';


export const metadata: Metadata = {
	title      : 'NextMatch',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>)
{
	return (
			<html lang="en" className="light">
			<body className="light">
				<Providers>
					<NavigationBar />
					<main className="min-h-screen container mx-auto p-8">
						{children}
					</main>
				</Providers>
			</body>
			</html>
	);
}
